# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20161102_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoVideoStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('video1', models.CharField(max_length=40)),
                ('video2', models.CharField(max_length=40)),
                ('chat', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
