# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FourVideoStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('video1', models.CharField(max_length=40)),
                ('video2', models.CharField(max_length=40)),
                ('video3', models.CharField(max_length=40)),
                ('video4', models.CharField(max_length=40)),
                ('chat', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SixVideoStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('video1', models.CharField(max_length=40)),
                ('video2', models.CharField(max_length=40)),
                ('video3', models.CharField(max_length=40)),
                ('video4', models.CharField(max_length=40)),
                ('video5', models.CharField(max_length=40)),
                ('video6', models.CharField(max_length=40)),
                ('chat', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
